from pydantic import BaseModel,Field
from typing import List

class EvalulationScore(BaseModel):
    score:int =Field(description="Score between 0 and 10",ge=0,le=10)


class KnowledgeRefinementResult(BaseModel):
    result:bool=Field(description="true if the sentence can answer the question ,false otherwise")


class RewritenQwery(BaseModel):
    rewritten_qwery:str=Field(description="the rewritten qwery to be used in web search")


class GeneratedResponce(BaseModel):
    answer:str=Field(description="the final answer generated by the model")
    answergiven:bool=Field(description="true if the model was able to give an answer ,false otherwise")